name: transcribe
description: "A Flutter app for converting speech to text"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
  - .env

flutter_native_splash:
  ios: true
  android: true
  color: "#000000"
  image: assets/images/app_icon.png
  