name: Build & Analyze

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          channel: stable

      - name: Load Google Services JSON File
        env: DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > android/app/google-services.json

      - name: Load Google Services PLIST File
        env: DATA: ${{ secrets.GOOGLE_SERVICES_PLIST }}
        run: echo $DATA | base64 -di > ios/Runner/GoogleService-Info.plist

      - name: Load ENV File
        env: DATA: ${{ secrets.ENV_FILE }}
        run: echo $DATA | base64 -di > .env

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project Source
        run: dart analyze --fatal-infos 